package com.parrot.tvmetadata.repositories;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;

@DynamoDBTable(tableName = "master_tv_metadata")
public class MasterTVMetaData implements Serializable {

    private String title;
    private String parrotId;

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "parrot_id")
    public String getParrotId() {
        return parrotId;
    }

    public void setParrotId(String parrotId) {
        this.parrotId = parrotId;
    }
}
